# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Picam360
email: info@picam360.com
description: > # this means to ignore newlines until "baseurl:"
  This project is a raspberry pi based panorama camera.
  Picam360 is opensource hardware and you can use its source code under GNU lisence.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://picam.github.io" # the base hostname & protocol for your site
twitter_username: picam360
github_username:  picam360
facebook_username:  picam360
include: [".well-known"]

# Build settings
markdown: kramdown
